version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: